Text Summarization Models

#Luhn's Heuristic Method

Summary for the text : Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline.

Source of the text : https://fox8.com/email-alerts/breaking-news-email-alerts/fire-breaks-out-at-in-kent-mill-district/


Importing library sumy


In [1]:
pip install sumy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 97 kB 2.0 MB/s 
     |████████████████████████████████| 10.1 MB 19.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for breadability: filename=breadability-0.1.20-py2.py3-none-any.whl size=21714 sha256=94aa57fec129c927fcc03e333991de00998ec9bc572a581154a6db7b2aebf5bb
  Stored in directory: /root/.cache/pip/wheels/5f/0d/0c/2062d8c1758b4b1a2e42b4a63e6660d9ec2ba9463cfee9eeab
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13723 sha256=c96f5d3cb5e3986c82ef672a102be0303e707c90218ed98bff0d1720c29c749f
  Stored in directory: /root/.cache/pip/wheels/56/ea/58/ead137b087d9e326852a851351d1debf4ada529b6ac0ec4e8c
  Created wheel for pycountry: filename=pycountry-22.3.5-py2.py3-none-any.whl size=10681845 sha256=7f004028eaaefc9a2f6c5c2b64

In [2]:
import sumy
import nltk
nltk.download('punkt')
from sumy.summarizers.luhn import LuhnSummarizer
from sumy.nlp.tokenizers import Tokenizer
from sumy.parsers.plaintext import PlaintextParser


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [3]:
source_material = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [4]:
LANGUAGE = "english"
parser = PlaintextParser.from_string(source_material,Tokenizer(LANGUAGE))

In [5]:
summarizer = LuhnSummarizer()

In [6]:
testsummary = summarizer(parser.document,sentences_count=3)

In [7]:
summary = ""
for sentence in testsummary:
  summary+=str(sentence)
print(summary)

The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion.According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use.Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour.


we obtain the following output: The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion.According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use.Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour.



 Evaluating using ROUGE METRICS


In [8]:
!pip install rouge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
from rouge import Rouge

In [10]:
reference = " Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [11]:
ROUGE = Rouge()
ROUGE.get_scores(summary,reference)

[{'rouge-1': {'r': 0.5874125874125874, 'p': 1.0, 'f': 0.7400881010646432},
  'rouge-2': {'r': 0.5047169811320755,
   'p': 0.981651376146789,
   'f': 0.666666662181462},
  'rouge-l': {'r': 0.5874125874125874, 'p': 1.0, 'f': 0.7400881010646432}}]

#TEXT RANK


In [12]:
!pip install gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
import gensim
from gensim.summarization import summarize

In [14]:
source_material = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [15]:
summary = summarize(source_material,word_count=100)

In [16]:
print(summary)

Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District.
The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion.
It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it.
They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues.


In [17]:

!pip install rouge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [18]:
from rouge import Rouge

In [19]:
reference ="Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [20]:
ROUGE = Rouge()
ROUGE.get_scores(summary,reference)

[{'rouge-1': {'r': 0.5944055944055944, 'p': 1.0, 'f': 0.7456140304112804},
  'rouge-2': {'r': 0.5188679245283019, 'p': 1.0, 'f': 0.683229809166313},
  'rouge-l': {'r': 0.5944055944055944, 'p': 1.0, 'f': 0.7456140304112804}}]

#Latent Semantic Analysis

In [21]:
!pip install sumy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
import sumy
import nltk
nltk.download('punkt')
from sumy.summarizers.lsa import LsaSummarizer
from sumy.nlp.tokenizers import Tokenizer
from sumy.parsers.plaintext import PlaintextParser

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [23]:
source_material = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [24]:
LANGUAGE = "english"
parser = PlaintextParser.from_string(source_material,Tokenizer(LANGUAGE))

In [25]:
summarizer = LsaSummarizer()

In [26]:
testsummary = summarizer(parser.document,sentences_count=4)

In [28]:
summary = ""
for sentence in testsummary:
  summary+=str(sentence)
print(summary)

Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District.The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion.It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it.It’s unclear how the building was currently being used.


In [29]:
!pip install rouge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [30]:
from rouge import Rouge

In [31]:
reference = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [33]:
ROUGE = Rouge()
ROUGE.get_scores(summary,reference)

[{'rouge-1': {'r': 0.5314685314685315, 'p': 1.0, 'f': 0.6940639224086237},
  'rouge-2': {'r': 0.44339622641509435,
   'p': 0.9894736842105263,
   'f': 0.6123778458890812},
  'rouge-l': {'r': 0.5314685314685315, 'p': 1.0, 'f': 0.6940639224086237}}]

#Kullback-Leibler Sum

In [34]:
!pip install sumy




Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [35]:

import sumy
import nltk
nltk.download('punkt')
from sumy.summarizers.kl import KLSummarizer
from sumy.nlp.tokenizers import Tokenizer
from sumy.parsers.plaintext import PlaintextParser

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [36]:
source_material = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [37]:
LANGUAGE = 'english'
parser = PlaintextParser.from_string(source_material,Tokenizer(LANGUAGE))

In [38]:
summarizer = KLSummarizer()

In [39]:
testsummary = summarizer(parser.document,sentences_count=6)

In [40]:
summary = ""
for sentence in testsummary:
  summary+=str(sentence)
print(summary)

They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues.According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use.The chief said fire operations could stretch into Saturday.No one was hurt in the fire.It’s unclear how the building was currently being used.The chief said no evacuations were issued.The iconic grain elevators are a well-known fixture in the city’s skyline.


In [41]:
!pip install rouge


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [42]:


from rouge import Rouge


In [43]:


reference = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [44]:
ROUGE = Rouge()
ROUGE.get_scores(summary,reference)

[{'rouge-1': {'r': 0.42657342657342656, 'p': 1.0, 'f': 0.5980392114941369},
  'rouge-2': {'r': 0.37264150943396224, 'p': 0.9875, 'f': 0.5410958864327267},
  'rouge-l': {'r': 0.42657342657342656, 'p': 1.0, 'f': 0.5980392114941369}}]

#T5 Transformer MOdel

In [45]:
!pip install transformers
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 24.6 MB/s 
     |████████████████████████████████| 182 kB 79.4 MB/s 
     |████████████████████████████████| 7.6 MB 60.7 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 33.0 MB/s 


In [46]:
import torch
import json
from transformers import T5Tokenizer, T5Config, T5ForConditionalGeneration

In [47]:
source_material = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [48]:
device = torch.device('cpu')

In [49]:

summarizer = T5ForConditionalGeneration.from_pretrained('t5-base')
tokenizer = T5Tokenizer.from_pretrained('t5-base')

Downloading:   0%|          | 0.00/1.20k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/892M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/792k [00:00<?, ?B/s]

/usr/local/lib/python3.8/dist-packages/transformers/models/t5/tokenization_t5.py:163: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(


In [50]:
updated_material = "summarize:" + source_material

In [51]:
tokenized_material = tokenizer.encode(updated_material, return_tensors="pt").to(device)


In [52]:
print(tokenized_material)


tensor([[21603,    10,   371,   521,  2687,    11,     3,     9,   508,  3681,
           526,    13,  7269,   228,    36,   894,    16,     8, 14599,   616,
          1701,    38,  4627,     7,  1279,    12,  1215,  1222,    76,  1273,
             3,     9,  3805,  1472,    16,     8, 19923,  4185,  3570,     5,
            37,  1472,  8238,    91,    44,  2042,    13,     8,  1244,  4185,
            53,   638,     5,   740,    44,   898,   357,   445,  2336,  1887,
           131,   274,   668,     3,     9,     5,    51,     5, 14599,  3655,
          5116,  3259,   499,   277,   243,    24,   220,   676,   227, 29764,
          4363,    44,     8,  3112,     6,   132,    47,    46, 16813,     5,
            94,    22,     7,    59,   964,   125,  2953,    34,     5,   634,
          1809,    13,     8,   740,    47, 22001,   227,     8, 16813,     6,
            78,  4627,     7,  2654,    22,    17,   281,  1096,    34,     5,
           328,  1279,    30,  1215,  1222,    76,  

In [53]:
tokenized_summary = summarizer.generate(tokenized_material,
                                    num_beams=5,
                                    no_repeat_ngram_size=2,
                                    min_length=100,
                                    max_length=120,
                                    early_stopping=True)


In [54]:
print(tokenized_summary)


tensor([[    0,     8,  1472,  8238,    91,    44,     8,  2042,    13,     8,
          1244,  4185,    53,   638,     5,   740,    44,   898,   357,   445,
          2336,  1887,   131,   274,   668,     3,     9,     5,    51,     5,
            34,    31,     7, 19363,   149,     8,   740,    47,  1083,   271,
           261,     3,     5,   150,    80,    47,  4781,    16,     8,     3,
         21020,     6,    11,   150, 29967,     7,    43,   118,  4683,    21,
             8,  5441,  3293,  3939,    13, 14599,     6,     3,    32,   107,
            23,    32,     6,   213,     8,  3293,   728,  2546,  3986,    13,
          4040,    13,  7051,    13,  7055,     5,     8, 10331,  8273, 19967,
             7,    33,   168,    18,  5661, 20420,    16,   690,    22,     7,
          5796,   747,     5,     1]])


In [55]:
summary = tokenizer.decode(tokenized_summary[0], skip_special_tokens=True)


In [57]:
print(summary)


the fire broke out at the Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. it's unclear how the building was currently being used. no one was hurt in the blaze, and no evacuations have been issued for the historic mill district of Kent, ohio, where the mill once produced hundreds of millions of pounds of flour. the iconic grain elevators are well-known fixture in city’s skyline.


In [58]:
!pip install rouge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [59]:
from rouge import Rouge


In [60]:
reference = "Flames and a large plume of smoke could be seen in the Kent area Friday as crews worked to extinguish a massive fire in the Historic Mill District. The fire broke out at Star of the West Milling Co. building at 162 N Water Street just before 9 a.m. Kent Fire Chief Bill Myers said that 3 minutes after firefighters arrived at the scene, there was an explosion. It’s not clear what caused it.The structure of the building was compromised after the explosion, so crews couldn’t go inside it. They worked on extinguishing the fire from the outside, the fire chief said.Chief Myers said they are also having some water supply issues. According to the chief, fighting the fire was taxing the water supply, so they were trying to reduce their use. The chief said fire operations could stretch into Saturday.No one was hurt in the fire. It’s unclear how the building was currently being used. The chief said no evacuations were issued. Kent State University issued an alert saying there is no threat to the campus but to avoid the downtown area.The cause of the fire is unknown.Named after the Williams Brothers in 1879, the Mill District of Kent, Ohio says the mill once produced hundreds of millions of pounds of flour. The iconic grain elevators are a well-known fixture in the city’s skyline."

In [61]:
ROUGE = Rouge()
ROUGE.get_scores(summary,reference)


[{'rouge-1': {'r': 0.34265734265734266,
   'p': 0.8448275862068966,
   'f': 0.4875621849488874},
  'rouge-2': {'r': 0.2358490566037736,
   'p': 0.6756756756756757,
   'f': 0.34965034581446525},
  'rouge-l': {'r': 0.3356643356643357,
   'p': 0.8275862068965517,
   'f': 0.4776119361926685}}]